# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the version of Python and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  apt_packages:
    - libclang-14-dev
    - gfortran
    - gcc
    - liblapack-dev
    - cmake
  jobs:
    post_create_environment:
      - mkdir build && cd build && cmake -DCMAKE_BUILD_TYPE=Release -DCMAKE_INSTALL_PREFIX=$READTHEDOCS_VIRTUALENV_PATH .. && make install
      - cd src/python_bindings/ && python setup.py install
    #pre_build:
    #  - mkdir $READTHEDOCS_OUTPUT
    #  - cd docs/Source && make html && mv _build/html $READTHEDOCS_OUTPUT

# Build documentation in the docs/ directory with Sphinx
sphinx:
   configuration: docs/Source/conf.py
   fail_on_warning: false

formats: all

# Optionally declare the Python requirements required to build your docs
python:
   install:
    - requirements: docs/Source/requirements.txt
    #- method: pip
    #  path: src/python_bindings/
      
